name: validate-creds
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Tests action
        uses: ./
        id: action-test
        with:
          aws-region: us-east-1
          vault-address: ${{ secrets.VAULT_ADDR }}
          vault-path: ${{ secrets.VAULT_PATH }}
          role-id: ${{ secrets.VAULT_ROLE_ID }}
          secret-id: ${{ secrets.VAULT_SECRET_ID }}
